dom/Gallerion - Django/mysite/gallery/urls.py
from django.contrib.auth.decorators import login_required
from views import *
from django.conf.urls import patterns, include, url
from django.contrib import admin
from mysite.settings import SITE_ROOT
import os

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^create/folder/$', login_required(CreateFolder.as_view()), name='create_folder'),
    url(r'^send/image$', login_required(SendImage.as_view()), name='send_image'),
    url(r'^send/image/progress$', login_required(ImageResizingWorkStatus.as_view()), name='image_send_state'),

    url(r'^$', Main.as_view(), name='main'),


    url(r'^config$', login_required(Config.as_view()), name='config'),

    url(r'^filter$', GetUserFolders.as_view(), name='get_users'),
    url(r'^filter/(?P<username>.*)/(?P<foldername>.*)/(?P<imagename>.*)$', GetImage.as_view(), name='get_image'),
    url(r'^filter/(?P<username>.*)/(?P<foldername>.*)$', GetImages.as_view(), name='get_images'),
    url(r'^filter/(?P<username>.*)$', GetFolders.as_view(), name='get_folders'),

    url(r'^resize/(?P<username>.*)/(?P<foldername>.*)/(?P<imagename>.*)/(?P<width>\d+)/$', ResizeImage.as_view(), name='resize_image'),
    url(r'^resize/progress$', ResisingImageStatus.as_view(), name='get_resize_state'),
    url(r'^resize/download', DownloadResizedImage.as_view(), name='download_resized_image'),

    url(r'^zip/(?P<user_name>.*)/(?P<folder_name>.*)$', GetZippedFolder.as_view(), name='get_zipped_folder'),
    url(r'^zip/progress$', login_required(ZippinWorkStatus.as_view()), name='get_zip_state'),
    url(r'^zip/download', login_required(DownloadZip.as_view()), name='download_zip'),

    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', login_required(Logout.as_view()), name='logout'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(SITE_ROOT, '../media/'), 'show_indexes': True}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(SITE_ROOT, '../static/'), 'show_indexes': True}),

    url(r'^admin/', include(admin.site.urls)),
)

dom/Gallerion - Django/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^', include('gallery.urls')),
)

dom/Gallerion - Django/mysite/gallery/models.py
from django.contrib.auth.models import User
from django.db import models


class Folder(models.Model):
    name = models.CharField(max_length=30)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.name


class ImageModel(models.Model):
    picture = models.ImageField(upload_to='images/')
    picture_thumb_large = models.ImageField(upload_to='thumbs/large/', blank=True)
    picture_thumb_medium = models.ImageField(upload_to='thumbs/medium/', blank=True)
    picture_thumb_small = models.ImageField(upload_to='thumbs/small/', blank=True)
    folder = models.ForeignKey(Folder)
    user = models.ForeignKey(User)
    name = models.CharField(max_length=50)


class ChangeFolderModel(models.Model):
    folder = models.ForeignKey(Folder)

    def __unicode__(self):
        return self.folder.name


class ConfigModel(models.Model):
    THUMBNAIL_TYPE = (
        ('large', 'Duze'),
        ('medium', 'Srednie'),
        ('small', 'Male'),
    )
    thumb_type = models.CharField(max_length=20, choices=THUMBNAIL_TYPE)
    user = models.ForeignKey(User)

dom/Gallerion - Django/mysite/gallery/forms.py
from django.forms import ModelForm, HiddenInput, TextInput, Form, CharField
from django import forms
from models import *



class CreateFolderForm(ModelForm):

    class Meta:
        model = Folder
        fields = [
            'name', 'user'
        ]
        widgets = {
            'user': HiddenInput(),
            'name': TextInput(attrs={'placeholder': 'Wpisz nazwe folderu',
                                     'name': 'Name',
                                     'id': 'id_name',
                                     'class': 'form-control'}),
        }

    def clean_name(self):
        data = self.cleaned_data['name']
        if len(data) < 1 or len(data) > 15:
            raise forms.ValidationError("Nazwa folderu nie moze byc mniejsza niz 1 i wieksza niz 15.")
        return data


class SendImageForm(ModelForm):

    class Meta:
        model = ImageModel
        fields = [
            'name', 'picture', 'user', 'folder'
        ]
        widgets = {
            'user': HiddenInput(),
        }

    def clean_name(self):
        data = self.cleaned_data['name']
        if len(data) < 1 or len(data) > 12:
            raise forms.ValidationError("Nazwa obrazku nie moze byc mniejsza niz 1 i wieksza niz 12.")
        return data

    def clean_picture(self):
        data = self.cleaned_data.get('picture', False)
        if data:
            if data._size > 1*1024*1024:
                raise forms.ValidationError("Plik za duzy - maksimum 1 Mb.")
            return data
        else:
            raise forms.ValidationError("Nie mozna bylo odczytac pliku.")


class ChangeFolderForm(Form):
    folder = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-control'}), queryset=Folder.objects.all())


class ConfigForm(ModelForm):

    class Meta:
        model = ConfigModel
        fields = [
            'thumb_type', 'user'
        ]
        THUMBNAIL_TYPE = (
            ('large', 'Duze'),
            ('medium', 'Srednie'),
            ('small', 'Male'),
        )
        widgets = {
            'user': HiddenInput(),
            'thumb_type': forms.Select(attrs={'class': 'form-control'})
        }

dom/Gallerion - Django/mysite/gallery/views.py
from django.views.generic import View
from django.shortcuts import render
from forms import *
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.core.urlresolvers import reverse
from django.http import Http404
from gallery.tasks import *
from PIL import Image
from django.core.files.uploadedfile import SimpleUploadedFile
import os
from cStringIO import StringIO
from mysite.settings import *
import zipfile
from celery.result import AsyncResult
from django.http import HttpResponse, HttpResponseRedirect


class CreateFolder(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'create_folder.html', {'form': CreateFolderForm(initial={'user': request.user})})

    def post(self, request, *args, **kwargs):
        form = CreateFolderForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            user = form.cleaned_data['user']

            if Folder.objects.all().filter(user=user).filter(name=name):
                return render(request, 'create_folder.html',
                              {'form': form, 'error': 'Folder o tej nazwie juz istnieje!'})
            else:
                form.save()
                return render(request, 'create_folder.html',
                              {'status': 'OK', 'form': CreateFolderForm(initial={'user': request.user})})
        else:
            return render(request, 'create_folder.html', {'form': form})


class ImageResizingWorkStatus(View):
    def get(self, request, *args, **kwargs):
        if 'job' in request.GET:
            job_id = request.GET['job']
        else:
            return HttpResponse('No job id given.')

        job = AsyncResult(job_id)
        time.sleep(0.5)
        if job.state == 'PENDING':
            return render(request, 'progress_bar_send_image.html', {'result': -1, 'status': 'Obraz przeslany. Oczekiwanie na Workera...'})

        elif job.state == 'PROGRESS':
            try:
                result = job.result['current']
            except TypeError:
                result = 99
                print 'aaa'
            return render(request, 'progress_bar_send_image.html', {'result': result, 'status': 'Obraz przeslany. Tworzenie miniatury...'})

        elif job.state == 'SUCCESS':
            thumbnail = job.result[0]
            content = job.result[1]
            pk = job.result[2]
            time.sleep(0.5)
            base_image = ImageModel.objects.all().filter(pk=pk).first()
            self.thumber_helper(base_image, thumbnail['large'], 'large', content)
            self.thumber_helper(base_image, thumbnail['medium'], 'medium', content)
            self.thumber_helper(base_image, thumbnail['small'], 'small', content)
            base_image = ImageModel.objects.all().filter(pk=pk).first()
            return render(request, 'progress_bar_send_image.html', {'result': 100, 'image': base_image})

        else:
            return render(request, 'progress_bar_send_image.html', {'result': -2})

    def thumber_helper(self, base_image, thumb, thumb_type, content):
        file_extension = content.split('/')[1]

        returned_stringed_image = StringIO(thumb)
        returned_opened_image = Image.open(returned_stringed_image)

        img_to_str_converter = StringIO()
        returned_opened_image.save(img_to_str_converter, file_extension)
        img_to_str_converter.seek(0)

        suf = SimpleUploadedFile(os.path.split(base_image.picture.name)[-1], img_to_str_converter.read(), content_type=content)

        if thumb_type == 'large':
            base_image.picture_thumb_large.save(
                '%s_thumbnail_%s.%s' % (os.path.splitext(suf.name)[0], 'large', file_extension), suf, save=False)
        elif thumb_type == 'medium':
            base_image.picture_thumb_medium.save(
                '%s_thumbnail_%s.%s' % (os.path.splitext(suf.name)[0], 'medium', file_extension), suf, save=False)
        elif thumb_type == 'small':
            base_image.picture_thumb_small.save(
                '%s_thumbnail_%s.%s' % (os.path.splitext(suf.name)[0], 'small', file_extension), suf, save=False)

        base_image.save()


class DownloadZip(View):
    def get(self, request, *args, **kwargs):
        if 'job' in request.GET:
            job_id = request.GET['job']
        else:
            return HttpResponse('No job id given.')

        job = AsyncResult(job_id)
        time.sleep(0.5)
        if job.state == 'SUCCESS':
            # zip_size = job.result[0]
            # zip_file = job.result[1]
            # time.sleep(0.5)
            # print zip_size
            # print len(zip_file)
            # while len(zip_file) != zip_size:
            #     pass
            # print 'bbbb'
            # resp = HttpResponse(zip_file, mimetype = "application/x-zip-compressed")
            # resp['Content-Disposition'] = 'attachment; filename=obrazki.zip'
            #
            # return resp
            res = job.result
            time.sleep(0.5)
            from django.shortcuts import redirect
            return redirect(res)

        # elif job.state == 'PROGRESS':
        #     zip_size = job.result[0]
        #     zip_file = job.result[1]
        #     time.sleep(0.5)
        #     print zip_size
        #     print len(zip_file)
        #     while len(zip_file) != zip_size:
        #         pass
        #     print 'ccc'
        #     resp = HttpResponse(zip_file, mimetype = "application/x-zip-compressed")
        #     resp['Content-Disposition'] = 'attachment; filename=obrazki.zip'
        #
        #     return resp

        else:
            print job.state
            return render(request, 'progress_bar_create_zip.html', {'result': -2})


class ZippinWorkStatus(View):
    def get(self, request, *args, **kwargs):
        if 'job' in request.GET:
            job_id = request.GET['job']
        else:
            return HttpResponse('No job id given.')

        job = AsyncResult(job_id)
        if job.state == 'PENDING':
            return render(request, 'progress_bar_create_zip.html', {'result': -1})

        elif job.state == 'PROGRESS':
            try:
                result = job.result['current']
            except TypeError:
                result = 99
            return render(request, 'progress_bar_create_zip.html', {'result': result, 'job_id': job.id})

        elif job.state == 'SUCCESS':
            return render(request, 'progress_bar_create_zip.html', {'result': 100, 'job_id': job.id})
        else:
            print job.state
            return render(request, 'progress_bar_create_zip.html', {'result': -2})


class DownloadResizedImage(View):
    def get(self, request, *args, **kwargs):
        if 'job' in request.GET:
            job_id = request.GET['job']
        else:
            return HttpResponse('No job id given.')

        job = AsyncResult(job_id)
        time.sleep(0.5)
        if job.state == 'SUCCESS':
            image_size = job.result[0]
            image_file = job.result[1]
            time.sleep(0.5)
            while len(image_file) != image_size:
                pass
            resp = HttpResponse(image_file, mimetype="image/jpg")
            resp['Content-Disposition'] = 'attachment; filename=obraz.jpg'
            return resp
        else:
            print job.state
            return render(request, 'progress_bar_create_zip.html', {'result': -2})


class ResisingImageStatus(View):
    def get(self, request, *args, **kwargs):
        if 'job' in request.GET:
            job_id = request.GET['job']
        else:
            return HttpResponse('No job id given.')

        job = AsyncResult(job_id)
        if job.state == 'PENDING':
            return render(request, 'progress_bar_resize_image.html', {'result': -1})

        elif job.state == 'PROGRESS':
            try:
                result = job.result['current']
            except TypeError:
                result = 99
            return render(request, 'progress_bar_resize_image.html', {'result': result, 'job_id': job.id})

        elif job.state == 'SUCCESS':
            return render(request, 'progress_bar_resize_image.html', {'result': 100, 'job_id': job.id})
        else:
            return render(request, 'progress_bar_resize_image.html', {'result': -2})


class SendImage(View):
    def get(self, request, *args, **kwargs):
        form = SendImageForm(initial={'user': request.user})
        form.fields["folder"].queryset = Folder.objects.filter(user=request.user)
        form.fields['name'].widget.attrs['class'] = "form-control"
        form.fields['folder'].widget.attrs['class'] = "form-control"
        return render(request, 'send_image.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = SendImageForm(request.POST, request.FILES)
        form.fields["folder"].queryset = Folder.objects.filter(user=request.user)
        form.fields['name'].widget.attrs['class'] = "form-control"
        form.fields['folder'].widget.attrs['class'] = "form-control"
        if form.is_valid():
            folder = Folder.objects.all().filter(name=form.cleaned_data['folder'].name)
            image = ImageModel.objects.all().filter(user=request.user).filter(folder=folder).filter(name=form.cleaned_data['name']).first()
            if image:
                return render(request, 'send_image.html', {'form': form, 'error': 'Obrazek o tej nazwie juz istnieje'})
            else:
                image_instance = form.instance
                content_type = image_instance.picture.file.content_type
                image_instance.save()

                job = create_thumb.delay('%s%s' % (SERVER_URL, image_instance.picture.url), content_type, image_instance.pk)

                return HttpResponseRedirect(reverse('image_send_state') + '?job=' + job.id)

        else:
            return render(request, 'send_image.html', {'form': form})


class Config(View):

dom/Gallerion - Django/mysite/gallery/templates/config.html
{% extends "base.html" %}

{% block content %}
    {% if form.thumb_type.errors %}
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Błąd!</strong> Popraw błędnie wprowadzone dane.
        </div>
    {% elif status %}
        <div class="alert alert-success">
            <strong>OK!</strong> Twoja konfiguracja została zapisana.
        </div>
    {% endif %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Konfiguracja</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" action="{% url 'config' %}" method="POST"
                  style="margin-left: auto; margin-right: auto; width: 600px">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name" class="col-sm-2 control-label" style="width: 200px">Wielkość miniatur</label>

                    <div class="col-sm-10" style="width: 200px">
                        {{ form.thumb_type }}
                        {{ form.user }}
                    </div>
                    <label class="col-sm-2 control-label" style="width: 200px">
                        {{ form.thumb_type.errors }}
                    </label>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-10">
                        <button type="submit" class="btn btn-default">Zapisz</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

dom/Gallerion - Django/mysite/gallery/templates/create_folder.html
{% extends "base.html" %}

{% block content %}
    {% if form.name.errors or error %}
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Błąd!</strong> Popraw błędnie wprowadzone dane.
        </div>
    {% elif status %}
        <div class="alert alert-success">
            <strong>OK!</strong> Folder został stworzony.
        </div>
    {% endif %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Stwórz folder</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" action="{% url 'create_folder' %}" method="POST"
                  style="margin-left: auto; margin-right: auto; width: 800px">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name" class="col-sm-2 control-label">Nazwa folderu</label>

                    <div class="col-sm-10" style="width: 300px">
                        {{ form.name }}
                        {{ form.user }}
                    </div>
                    <label class="col-sm-2 control-label" style="width: 300px">
                        {% if error %}
                            <ul class="errorlist">
                                <li>{{ error }}</li>
                            </ul>
                        {% else %}
                            {{ form.name.errors }}
                        {% endif %}
                    </label>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">Stwórz</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

dom/Gallerion - Django/mysite/gallery/templates/folder_list.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
    {% if status %}
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>OK!</strong> Obrazek został przeniesiony.
        </div>
    {% endif %}

    <div class="bs-example">
        <div class="row">

            {% for folder in folder_list %}
                <div class="col-xs-6 col-md-3">
                    <a href="{% url 'get_images' folder.user.username folder.name %}" class="thumbnail">
                        <img src="{% static 'gallery/images/folder.png' %}"
                             style="height: 220px; width: 100%; display: block;" data-src="holder.js/100%x180"
                             alt="{{ folder.name }}">
                        <span class="glyphicon-class" style="text-align: center"><h3>{{ folder.name }}</h3></span>
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

dom/Gallerion - Django/mysite/gallery/templates/fullwidth.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1 style="text-align: center;">Gallerion</h1>
  <h2 style="text-align: center;">Twoja galeria zdjęć...</h2>
</div>
{% endblock content %}

dom/Gallerion - Django/mysite/gallery/templates/image_list.html
{% extends "base.html" %}

{% block content %}

    <div class="bs-example">
        <div class="row">

            {% for image in image_list %}
                {% if type == 'small' %}
                    <div class="col-xs-6 col-md-3" style="width: 90px;">
                {% elif type == 'medium' %}
                    <div class="col-xs-6 col-md-3" style="width: 190px;">
                {% else %}
                    <div class="col-xs-6 col-md-3" style="width: 290px;">
                {% endif %}


                    {% if type == 'small' %}
                        <a href="{% url 'get_image' image.user.username image.folder.name image.name %}" class="thumbnail" style="padding: 0; width: 70px; height: 70px">
                        {% if image.picture_thumb_small %}
                            <img src="{{ image.picture_thumb_small.url }}" style=" display: block;" alt="{{ image.name }}">
                        {% else %}
                            <span class="glyphicon-class" style="text-align: center"><h5>{{ image.name }}</h5></span>
                        {% endif %}
                    {% elif type == 'medium' %}
                        <a href="{% url 'get_image' image.user.username image.folder.name image.name %}" class="thumbnail" style="padding: 0; width: 170px; height: 170px">
                        {% if image.picture_thumb_medium %}
                            <img src="{{ image.picture_thumb_medium.url }}" style=" display: block;" alt="{{ image.name }}">
                        {% else %}
                            <span class="glyphicon-class" style="text-align: center"><h5>{{ image.name }}</h5></span>
                        {% endif %}
                    {% else %}
                        <a href="{% url 'get_image' image.user.username image.folder.name image.name %}" class="thumbnail" style="padding: 0; width: 270px; height: 270px">
                        {% if image.picture_thumb_large %}
                            <img src="{{ image.picture_thumb_large.url }}" style=" display: block;" alt="{{ image.name }}">
                        {% else %}
                            <span class="glyphicon-class" style="text-align: center"><h5>{{ image.name }}</h5></span>
                        {% endif %}
                    {% endif %}
                    </a>
                </div>
            {% endfor %}

        </div>
        {% if image_list.count != 0 %}
            <a class="btn btn-default" style="float: right" href="{% url 'get_zipped_folder' username foldername %}">Pobierz folder</a>
        {% endif %}
    </div>

{% endblock %}

dom/Gallerion - Django/mysite/gallery/templates/login.html
{% extends "base.html" %}

{% block content %}

    {% if error %}
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Błąd!</strong> {{ error }}
        </div>
    {% endif %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Zaloguj się</h3>
        </div>
        <div class="panel-body">

            <form class="form-inline" role="form" action="" method="POST" style="margin-left: auto; margin-right: auto; width: 476px">
                {% csrf_token %}

                <div class="form-group">
                    <label class="sr-only" for="id_username">Login</label>
                    {{ form.username }}
                </div>

                <div class="form-group">
                    <label class="sr-only" for="id_password">Hasło</label>
                    {{ form.password }}
                </div>

                <button type="submit" class="btn btn-default">Zaloguj</button>

            </form>
        </div>
    </div>

{% endblock %}

dom/Gallerion - Django/mysite/gallery/templates/ok.html
{% extends "base.html" %}

{% block config %}
    <meta http-equiv="refresh" content="3;url={% url 'main' %}">
{% endblock %}

{% block content %}
    <div class="alert alert-success">
        <strong>OK!</strong> {{ text }}
    </div>
{% endblock %}

dom/Gallerion - Django/mysite/gallery/templates/send_image.html
{% extends "base.html" %}

{% block config %}
    <script src="//code.jquery.com/jquery-2.1.1.js"></script>
{% endblock %}

{% block content %}

    {% if form.name.errors or form.folder.errors or form.picture.errors or error %}
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Błąd!</strong> Popraw błędnie wprowadzone dane.
        </div>
    {% endif %}

    <div class="panel panel-default">

        <div class="panel-heading">
            <h3 class="panel-title">Dodaj obraz</h3>
        </div>

        <div class="panel-body">

            <form class="form-horizontal" enctype="multipart/form-data" action="{% url 'send_image' %}" method="POST"
                  style="margin-left: auto; margin-right: auto; width: 800px">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_name" class="col-sm-2 control-label">Nazwa obrazka</label>

                    <div class="col-sm-10" style="width: 300px">
                        {{ form.name }}
                    </div>
                    <label class="col-sm-2 control-label" style="width: 300px">
                        {% if error %}
                            <ul class="errorlist">
                                <li>{{ error }}</li>
                            </ul>
                        {% else %}
                            {{ form.name.errors }}
                        {% endif %}
                    </label>
                </div>

                <div class="form-group">
                    <label for="id_folder" class="col-sm-2 control-label">Folder</label>

                    <div class="col-sm-10" style="width: 300px">
                        {{ form.folder }}
                    </div>
                    <label class="col-sm-2 control-label" style="width: 300px">
                        {{ form.folder.errors }}
                    </label>
                </div>

                <div class="form-group">
                    <label for="id_folder" class="col-sm-2 control-label">Obraz</label>

                    <div class="col-sm-10" style="width: 300px">
                        {{ form.picture }}
                    </div>
                    <label class="col-sm-2 control-label" style="width: 600px">
                        {{ form.picture.errors }}
                    </label>
                </div>

                <script type="text/javascript">
                    $('#id_picture').bind('change', function () {
                        var size = this.files[0].size / 1024 / 1024;
                        if (size >= 1) {
                            alert('Obrazek jest za duży! Maksymalny rozmiar to 1MB, aktualny ' + Math.round(this.files[0].size / 1024 / 1024*100)/100 + "MB");
                            document.getElementById("id_picture").value = "";
                        }
                    });
                </script>
                {{ form.user }}

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">Prześlij</button>
                    </div>
                </div>

            </form>

        </div>

    </div>
{% endblock %}

dom/Gallerion - Django/mysite/gallery/templates/show_image.html
{% extends "base.html" %}

{% block content %}
    <div class="well well-lg" style="text-align: center">
        <img src="{{ image.picture.url }}" alt="{{ image.name }}" style="height: 100%; width: 600px;"/>
    </div>

    {% if form.folder.errors %}
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Błąd!</strong> Musisz wybrać folder.
        </div>
    {% endif %}

    <a class="btn btn-default" style="float: right; margin-left: 20px" href="{{ image.picture.url }}"
           download="{{ image.name }}.{{ image_format }}">Pobierz w
            oryginalnym rozmiarze</a>

    <div class="btn-group" style="float: right">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Pobierz w rozmiarze... <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'resize_image' image.user.username image.folder.name image.name 100 %}">W-100</a></li>
            <li><a href="{% url 'resize_image' image.user.username image.folder.name image.name 300 %}">W-300</a></li>
            <li><a href="{% url 'resize_image' image.user.username image.folder.name image.name 500 %}">W-500</a></li>
            <li><a href="{% url 'resize_image' image.user.username image.folder.name image.name 700 %}">W-700</a></li>
            <li><a href="{% url 'resize_image' image.user.username image.folder.name image.name 900 %}">W-900</a></li>
        </ul>
    </div>

    {% if user_folder %}
        <div class="panel panel-default" style="width:450px">
            <div class="panel-heading">
                <h3 class="panel-title">Przenieś do folderu</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="id_folder" style="width: 140px; padding-top: 5px">Nazwa
                            folderu</label>
                        {{ form.folder }}
                    </div>
                    <button type="submit" class="btn btn-default" style="margin-left: 10px">Przenies</button>
                </form>
            </div>
        </div>
    {% endif %}

{% endblock %}

dom/Gallerion - Django/mysite/gallery/templates/user_folder_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

    <div class="bs-example">
        <div class="row">

            {% for user in folder_list %}
                <div class="col-xs-6 col-md-3">
                    <a href="{% url 'get_folders' user %}" class="thumbnail">
                        <img src="{% static 'gallery/images/user.png' %}"
                             style="height: 220px; width: 100%; display: block;" data-src="holder.js/100%x180"
                             alt="{{ user }}">
                        <span class="glyphicon-class" style="text-align: center"><h3>{{ user }}</h3></span>
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}